services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./src/ugtsic_project:/src/ugtsic_project
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    env_file:
      - ./.env
    depends_on:
      - psql
    command: ["bash", "/scripts/commands.sh"]

  psql:
    container_name: ugtsic_db
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env